### PR TITLE
Changes to build with morty 2.2 release

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by kraj** [comment]
This pull request make the branch build with morty and master branches of OE-Core. Please merge

**Comment by kraj** [comment]
I wonder why this patchset is still not accepted yet ?

**Comment by vkonstantins** [comment]
The Morty development continues in meta-variscite-fslc
The required patches are there.
Thank you for posting.

**Review by vkonstantins — APPROVED** [review]

**Review by vkonstantins — APPROVED** [review]

**Comment by kraj** [comment]
@vkonstantins I am trying to build with pyro/yocto-2.3 release for imx6ul-var-dart board so you recommend I use meta-variscite-fslc and not meta-variscite-imx ? I wish there was just one layer something like meta-variscite which contained all SOMs support and releases followed the yocto release branch names. it would be so easy

**Comment by floion** [comment]
Hi @vkonstantins so the preferred BSP layer is actually https://github.com/varigit/meta-variscite-fslc and not this one?

**Comment by eranmati** [comment]
Hi @floion 
We use https://github.com/varigit/meta-variscite-imx for builds based on official NXP releases.
We used it for our mx6/6ul/7 releases prior to Yocto Morty, and for our current mx8 Yocto Morty release.

We use https://github.com/varigit/meta-variscite-fslc for builds based on the fsl community BSP.
We use it for our mx6/6ul/7 releases starting from Yocto Morty.

Please see:
www.variwiki.com

Also, next time please post your questions in the Variscite customer portal:
https://varisciteportal.axosoft.com

Regards,
Eran

**Comment by floion** [comment]
Thanks for the reply

**Pull request closed without merging**
